language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - coverity_scan
env:
  global:
    - secure: "lN/1nBJvrLsBhDRJwoAKiu5Xv9dRyH7EJ4DC1AUgRfaz/2in8e9X8psluCxXiCkUqxJqjqIwp/IUWJyIgnUj1Tj8KT2dyR/wp68Q+tr3buRxGbZf9lAIirj44LB7ji5cxGKmuvJNY3M5hFaLoovquqacwB0FslnhssH/HpuSHMC2lyNXxnIduTLha/7AZAX7+xNTeRQ86cpVIh5/UJEhvqICdlywhsguAdeyyI/ZLRElLY07O3R9SJAaOgy95oDmSwq3IflIjBNhlxrWKYUUAkQFjM3HdwcmLbhP5aZAJWbrDRiAeXzJyqgvvo/oHS+AtSc8r68TvZ+O+H4d0XLbExrz4cFdXHKCJY/OuI6pwpXRWoXiPgEBpNodef5iGupU84ZxKiBGvSWEJNgGDSHLwUgVzEtOSPnvmeVGRHHi2hO9onOMKHPsJR8aHWg8VDcsf3kXIF7YVC2lvaO5Ubi9ESzjBoE3tQsQlcaHCOzYsXqI70DAH4lgZtabYRIWbFcbl+RSoNsrvh5HhMl17W0YM1a3+bXdF/Q926jFg506XDvYhyPy2DUoiwnSdtthxMJYYLTDSYjZDzykmCH0A2TM+iM2hJLP8LO/b7wLxj/lI2NhmRQzhI8pMhkBHa97kMH3eTX+QZYJt9PJR+MyixcBzcOaTLLm2kBoPZOFU7oKgI8="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-push-server"
      description: "Build submitted via Travis CI"
    notification_email: roman.strobl@wultra.com
    build_command_prepend: "mvn clean"
    build_command: "mvn compile -DskipTests=true"
    branch_pattern: coverity_scan